package com.zx.bean;

public class BookMark extends BookMarkKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookmark.bookmark_title
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    private String bookmarkTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookmark.bookmark_content
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    private String bookmarkContent;

    public BookMark() {
    }

    public BookMark(Integer bookmarkId, Integer userId, String bookmarkTitle, String bookmarkContent) {
        super(bookmarkId, userId);
        this.bookmarkTitle = bookmarkTitle;
        this.bookmarkContent = bookmarkContent;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookmark.bookmark_title
     *
     * @return the value of bookmark.bookmark_title
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public String getBookmarkTitle() {
        return bookmarkTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookmark.bookmark_title
     *
     * @param bookmarkTitle the value for bookmark.bookmark_title
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public void setBookmarkTitle(String bookmarkTitle) {
        this.bookmarkTitle = bookmarkTitle == null ? null : bookmarkTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookmark.bookmark_content
     *
     * @return the value of bookmark.bookmark_content
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public String getBookmarkContent() {
        return bookmarkContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookmark.bookmark_content
     *
     * @param bookmarkContent the value for bookmark.bookmark_content
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public void setBookmarkContent(String bookmarkContent) {
        this.bookmarkContent = bookmarkContent == null ? null : bookmarkContent.trim();
    }
}