package com.zx.bean;

import java.util.ArrayList;
import java.util.List;

public class BookMarkExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bookmark
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bookmark
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bookmark
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public BookMarkExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bookmark
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBookmarkIdIsNull() {
            addCriterion("bookmark_id is null");
            return (Criteria) this;
        }

        public Criteria andBookmarkIdIsNotNull() {
            addCriterion("bookmark_id is not null");
            return (Criteria) this;
        }

        public Criteria andBookmarkIdEqualTo(Integer value) {
            addCriterion("bookmark_id =", value, "bookmarkId");
            return (Criteria) this;
        }

        public Criteria andBookmarkIdNotEqualTo(Integer value) {
            addCriterion("bookmark_id <>", value, "bookmarkId");
            return (Criteria) this;
        }

        public Criteria andBookmarkIdGreaterThan(Integer value) {
            addCriterion("bookmark_id >", value, "bookmarkId");
            return (Criteria) this;
        }

        public Criteria andBookmarkIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("bookmark_id >=", value, "bookmarkId");
            return (Criteria) this;
        }

        public Criteria andBookmarkIdLessThan(Integer value) {
            addCriterion("bookmark_id <", value, "bookmarkId");
            return (Criteria) this;
        }

        public Criteria andBookmarkIdLessThanOrEqualTo(Integer value) {
            addCriterion("bookmark_id <=", value, "bookmarkId");
            return (Criteria) this;
        }

        public Criteria andBookmarkIdIn(List<Integer> values) {
            addCriterion("bookmark_id in", values, "bookmarkId");
            return (Criteria) this;
        }

        public Criteria andBookmarkIdNotIn(List<Integer> values) {
            addCriterion("bookmark_id not in", values, "bookmarkId");
            return (Criteria) this;
        }

        public Criteria andBookmarkIdBetween(Integer value1, Integer value2) {
            addCriterion("bookmark_id between", value1, value2, "bookmarkId");
            return (Criteria) this;
        }

        public Criteria andBookmarkIdNotBetween(Integer value1, Integer value2) {
            addCriterion("bookmark_id not between", value1, value2, "bookmarkId");
            return (Criteria) this;
        }

        public Criteria andBookmarkTitleIsNull() {
            addCriterion("bookmark_title is null");
            return (Criteria) this;
        }

        public Criteria andBookmarkTitleIsNotNull() {
            addCriterion("bookmark_title is not null");
            return (Criteria) this;
        }

        public Criteria andBookmarkTitleEqualTo(String value) {
            addCriterion("bookmark_title =", value, "bookmarkTitle");
            return (Criteria) this;
        }

        public Criteria andBookmarkTitleNotEqualTo(String value) {
            addCriterion("bookmark_title <>", value, "bookmarkTitle");
            return (Criteria) this;
        }

        public Criteria andBookmarkTitleGreaterThan(String value) {
            addCriterion("bookmark_title >", value, "bookmarkTitle");
            return (Criteria) this;
        }

        public Criteria andBookmarkTitleGreaterThanOrEqualTo(String value) {
            addCriterion("bookmark_title >=", value, "bookmarkTitle");
            return (Criteria) this;
        }

        public Criteria andBookmarkTitleLessThan(String value) {
            addCriterion("bookmark_title <", value, "bookmarkTitle");
            return (Criteria) this;
        }

        public Criteria andBookmarkTitleLessThanOrEqualTo(String value) {
            addCriterion("bookmark_title <=", value, "bookmarkTitle");
            return (Criteria) this;
        }

        public Criteria andBookmarkTitleLike(String value) {
            addCriterion("bookmark_title like", value, "bookmarkTitle");
            return (Criteria) this;
        }

        public Criteria andBookmarkTitleNotLike(String value) {
            addCriterion("bookmark_title not like", value, "bookmarkTitle");
            return (Criteria) this;
        }

        public Criteria andBookmarkTitleIn(List<String> values) {
            addCriterion("bookmark_title in", values, "bookmarkTitle");
            return (Criteria) this;
        }

        public Criteria andBookmarkTitleNotIn(List<String> values) {
            addCriterion("bookmark_title not in", values, "bookmarkTitle");
            return (Criteria) this;
        }

        public Criteria andBookmarkTitleBetween(String value1, String value2) {
            addCriterion("bookmark_title between", value1, value2, "bookmarkTitle");
            return (Criteria) this;
        }

        public Criteria andBookmarkTitleNotBetween(String value1, String value2) {
            addCriterion("bookmark_title not between", value1, value2, "bookmarkTitle");
            return (Criteria) this;
        }

        public Criteria andBookmarkContentIsNull() {
            addCriterion("bookmark_content is null");
            return (Criteria) this;
        }

        public Criteria andBookmarkContentIsNotNull() {
            addCriterion("bookmark_content is not null");
            return (Criteria) this;
        }

        public Criteria andBookmarkContentEqualTo(String value) {
            addCriterion("bookmark_content =", value, "bookmarkContent");
            return (Criteria) this;
        }

        public Criteria andBookmarkContentNotEqualTo(String value) {
            addCriterion("bookmark_content <>", value, "bookmarkContent");
            return (Criteria) this;
        }

        public Criteria andBookmarkContentGreaterThan(String value) {
            addCriterion("bookmark_content >", value, "bookmarkContent");
            return (Criteria) this;
        }

        public Criteria andBookmarkContentGreaterThanOrEqualTo(String value) {
            addCriterion("bookmark_content >=", value, "bookmarkContent");
            return (Criteria) this;
        }

        public Criteria andBookmarkContentLessThan(String value) {
            addCriterion("bookmark_content <", value, "bookmarkContent");
            return (Criteria) this;
        }

        public Criteria andBookmarkContentLessThanOrEqualTo(String value) {
            addCriterion("bookmark_content <=", value, "bookmarkContent");
            return (Criteria) this;
        }

        public Criteria andBookmarkContentLike(String value) {
            addCriterion("bookmark_content like", value, "bookmarkContent");
            return (Criteria) this;
        }

        public Criteria andBookmarkContentNotLike(String value) {
            addCriterion("bookmark_content not like", value, "bookmarkContent");
            return (Criteria) this;
        }

        public Criteria andBookmarkContentIn(List<String> values) {
            addCriterion("bookmark_content in", values, "bookmarkContent");
            return (Criteria) this;
        }

        public Criteria andBookmarkContentNotIn(List<String> values) {
            addCriterion("bookmark_content not in", values, "bookmarkContent");
            return (Criteria) this;
        }

        public Criteria andBookmarkContentBetween(String value1, String value2) {
            addCriterion("bookmark_content between", value1, value2, "bookmarkContent");
            return (Criteria) this;
        }

        public Criteria andBookmarkContentNotBetween(String value1, String value2) {
            addCriterion("bookmark_content not between", value1, value2, "bookmarkContent");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bookmark
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 06 09:27:53 HKT 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bookmark
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}