package com.zx.bean;

public class BookMarkKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookmark.bookmark_id
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    private Integer bookmarkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookmark.user_id
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    private Integer userId;

    public BookMarkKey() {
    }

    public BookMarkKey(Integer bookmarkId, Integer userId) {
        this.bookmarkId = bookmarkId;
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookmark.bookmark_id
     *
     * @return the value of bookmark.bookmark_id
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public Integer getBookmarkId() {
        return bookmarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookmark.bookmark_id
     *
     * @param bookmarkId the value for bookmark.bookmark_id
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public void setBookmarkId(Integer bookmarkId) {
        this.bookmarkId = bookmarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookmark.user_id
     *
     * @return the value of bookmark.user_id
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookmark.user_id
     *
     * @param userId the value for bookmark.user_id
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}