package com.zx.bean;

public class BookMark {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookmark.bookmark_id
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    private Integer bookmarkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookmark.bookmark_title
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    private String bookmarkTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookmark.bookmark_content
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    private String bookmarkContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookmark.user_id
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    private Integer userId;

    public BookMark() {
    }

    public BookMark(Integer bookmarkId, String bookmarkTitle, String bookmarkContent, Integer userId) {
        this.bookmarkId = bookmarkId;
        this.bookmarkTitle = bookmarkTitle;
        this.bookmarkContent = bookmarkContent;
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookmark.bookmark_id
     *
     * @return the value of bookmark.bookmark_id
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public Integer getBookmarkId() {
        return bookmarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookmark.bookmark_id
     *
     * @param bookmarkId the value for bookmark.bookmark_id
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public void setBookmarkId(Integer bookmarkId) {
        this.bookmarkId = bookmarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookmark.bookmark_title
     *
     * @return the value of bookmark.bookmark_title
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public String getBookmarkTitle() {
        return bookmarkTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookmark.bookmark_title
     *
     * @param bookmarkTitle the value for bookmark.bookmark_title
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public void setBookmarkTitle(String bookmarkTitle) {
        this.bookmarkTitle = bookmarkTitle == null ? null : bookmarkTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookmark.bookmark_content
     *
     * @return the value of bookmark.bookmark_content
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public String getBookmarkContent() {
        return bookmarkContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookmark.bookmark_content
     *
     * @param bookmarkContent the value for bookmark.bookmark_content
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public void setBookmarkContent(String bookmarkContent) {
        this.bookmarkContent = bookmarkContent == null ? null : bookmarkContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookmark.user_id
     *
     * @return the value of bookmark.user_id
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookmark.user_id
     *
     * @param userId the value for bookmark.user_id
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}