package com.zx.bean;

import java.util.ArrayList;
import java.util.List;

public class CalendarExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calendar
     *
     * @mbg.generated Fri May 29 14:34:05 HKT 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calendar
     *
     * @mbg.generated Fri May 29 14:34:05 HKT 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calendar
     *
     * @mbg.generated Fri May 29 14:34:05 HKT 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbg.generated Fri May 29 14:34:05 HKT 2020
     */
    public CalendarExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbg.generated Fri May 29 14:34:05 HKT 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbg.generated Fri May 29 14:34:05 HKT 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbg.generated Fri May 29 14:34:05 HKT 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbg.generated Fri May 29 14:34:05 HKT 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbg.generated Fri May 29 14:34:05 HKT 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbg.generated Fri May 29 14:34:05 HKT 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbg.generated Fri May 29 14:34:05 HKT 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbg.generated Fri May 29 14:34:05 HKT 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbg.generated Fri May 29 14:34:05 HKT 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbg.generated Fri May 29 14:34:05 HKT 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calendar
     *
     * @mbg.generated Fri May 29 14:34:05 HKT 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCalendarIdIsNull() {
            addCriterion("calendar_id is null");
            return (Criteria) this;
        }

        public Criteria andCalendarIdIsNotNull() {
            addCriterion("calendar_id is not null");
            return (Criteria) this;
        }

        public Criteria andCalendarIdEqualTo(Integer value) {
            addCriterion("calendar_id =", value, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdNotEqualTo(Integer value) {
            addCriterion("calendar_id <>", value, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdGreaterThan(Integer value) {
            addCriterion("calendar_id >", value, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("calendar_id >=", value, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdLessThan(Integer value) {
            addCriterion("calendar_id <", value, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdLessThanOrEqualTo(Integer value) {
            addCriterion("calendar_id <=", value, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdIn(List<Integer> values) {
            addCriterion("calendar_id in", values, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdNotIn(List<Integer> values) {
            addCriterion("calendar_id not in", values, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdBetween(Integer value1, Integer value2) {
            addCriterion("calendar_id between", value1, value2, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdNotBetween(Integer value1, Integer value2) {
            addCriterion("calendar_id not between", value1, value2, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarTitleIsNull() {
            addCriterion("calendar_title is null");
            return (Criteria) this;
        }

        public Criteria andCalendarTitleIsNotNull() {
            addCriterion("calendar_title is not null");
            return (Criteria) this;
        }

        public Criteria andCalendarTitleEqualTo(String value) {
            addCriterion("calendar_title =", value, "calendarTitle");
            return (Criteria) this;
        }

        public Criteria andCalendarTitleNotEqualTo(String value) {
            addCriterion("calendar_title <>", value, "calendarTitle");
            return (Criteria) this;
        }

        public Criteria andCalendarTitleGreaterThan(String value) {
            addCriterion("calendar_title >", value, "calendarTitle");
            return (Criteria) this;
        }

        public Criteria andCalendarTitleGreaterThanOrEqualTo(String value) {
            addCriterion("calendar_title >=", value, "calendarTitle");
            return (Criteria) this;
        }

        public Criteria andCalendarTitleLessThan(String value) {
            addCriterion("calendar_title <", value, "calendarTitle");
            return (Criteria) this;
        }

        public Criteria andCalendarTitleLessThanOrEqualTo(String value) {
            addCriterion("calendar_title <=", value, "calendarTitle");
            return (Criteria) this;
        }

        public Criteria andCalendarTitleLike(String value) {
            addCriterion("calendar_title like", value, "calendarTitle");
            return (Criteria) this;
        }

        public Criteria andCalendarTitleNotLike(String value) {
            addCriterion("calendar_title not like", value, "calendarTitle");
            return (Criteria) this;
        }

        public Criteria andCalendarTitleIn(List<String> values) {
            addCriterion("calendar_title in", values, "calendarTitle");
            return (Criteria) this;
        }

        public Criteria andCalendarTitleNotIn(List<String> values) {
            addCriterion("calendar_title not in", values, "calendarTitle");
            return (Criteria) this;
        }

        public Criteria andCalendarTitleBetween(String value1, String value2) {
            addCriterion("calendar_title between", value1, value2, "calendarTitle");
            return (Criteria) this;
        }

        public Criteria andCalendarTitleNotBetween(String value1, String value2) {
            addCriterion("calendar_title not between", value1, value2, "calendarTitle");
            return (Criteria) this;
        }

        public Criteria andCalendarContentIsNull() {
            addCriterion("calendar_content is null");
            return (Criteria) this;
        }

        public Criteria andCalendarContentIsNotNull() {
            addCriterion("calendar_content is not null");
            return (Criteria) this;
        }

        public Criteria andCalendarContentEqualTo(String value) {
            addCriterion("calendar_content =", value, "calendarContent");
            return (Criteria) this;
        }

        public Criteria andCalendarContentNotEqualTo(String value) {
            addCriterion("calendar_content <>", value, "calendarContent");
            return (Criteria) this;
        }

        public Criteria andCalendarContentGreaterThan(String value) {
            addCriterion("calendar_content >", value, "calendarContent");
            return (Criteria) this;
        }

        public Criteria andCalendarContentGreaterThanOrEqualTo(String value) {
            addCriterion("calendar_content >=", value, "calendarContent");
            return (Criteria) this;
        }

        public Criteria andCalendarContentLessThan(String value) {
            addCriterion("calendar_content <", value, "calendarContent");
            return (Criteria) this;
        }

        public Criteria andCalendarContentLessThanOrEqualTo(String value) {
            addCriterion("calendar_content <=", value, "calendarContent");
            return (Criteria) this;
        }

        public Criteria andCalendarContentLike(String value) {
            addCriterion("calendar_content like", value, "calendarContent");
            return (Criteria) this;
        }

        public Criteria andCalendarContentNotLike(String value) {
            addCriterion("calendar_content not like", value, "calendarContent");
            return (Criteria) this;
        }

        public Criteria andCalendarContentIn(List<String> values) {
            addCriterion("calendar_content in", values, "calendarContent");
            return (Criteria) this;
        }

        public Criteria andCalendarContentNotIn(List<String> values) {
            addCriterion("calendar_content not in", values, "calendarContent");
            return (Criteria) this;
        }

        public Criteria andCalendarContentBetween(String value1, String value2) {
            addCriterion("calendar_content between", value1, value2, "calendarContent");
            return (Criteria) this;
        }

        public Criteria andCalendarContentNotBetween(String value1, String value2) {
            addCriterion("calendar_content not between", value1, value2, "calendarContent");
            return (Criteria) this;
        }

        public Criteria andCalendarTimeIsNull() {
            addCriterion("calendar_time is null");
            return (Criteria) this;
        }

        public Criteria andCalendarTimeIsNotNull() {
            addCriterion("calendar_time is not null");
            return (Criteria) this;
        }

        public Criteria andCalendarTimeEqualTo(String value) {
            addCriterion("calendar_time =", value, "calendarTime");
            return (Criteria) this;
        }

        public Criteria andCalendarTimeNotEqualTo(String value) {
            addCriterion("calendar_time <>", value, "calendarTime");
            return (Criteria) this;
        }

        public Criteria andCalendarTimeGreaterThan(String value) {
            addCriterion("calendar_time >", value, "calendarTime");
            return (Criteria) this;
        }

        public Criteria andCalendarTimeGreaterThanOrEqualTo(String value) {
            addCriterion("calendar_time >=", value, "calendarTime");
            return (Criteria) this;
        }

        public Criteria andCalendarTimeLessThan(String value) {
            addCriterion("calendar_time <", value, "calendarTime");
            return (Criteria) this;
        }

        public Criteria andCalendarTimeLessThanOrEqualTo(String value) {
            addCriterion("calendar_time <=", value, "calendarTime");
            return (Criteria) this;
        }

        public Criteria andCalendarTimeLike(String value) {
            addCriterion("calendar_time like", value, "calendarTime");
            return (Criteria) this;
        }

        public Criteria andCalendarTimeNotLike(String value) {
            addCriterion("calendar_time not like", value, "calendarTime");
            return (Criteria) this;
        }

        public Criteria andCalendarTimeIn(List<String> values) {
            addCriterion("calendar_time in", values, "calendarTime");
            return (Criteria) this;
        }

        public Criteria andCalendarTimeNotIn(List<String> values) {
            addCriterion("calendar_time not in", values, "calendarTime");
            return (Criteria) this;
        }

        public Criteria andCalendarTimeBetween(String value1, String value2) {
            addCriterion("calendar_time between", value1, value2, "calendarTime");
            return (Criteria) this;
        }

        public Criteria andCalendarTimeNotBetween(String value1, String value2) {
            addCriterion("calendar_time not between", value1, value2, "calendarTime");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calendar
     *
     * @mbg.generated do_not_delete_during_merge Fri May 29 14:34:05 HKT 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calendar
     *
     * @mbg.generated Fri May 29 14:34:05 HKT 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}