package com.zx.bean;

public class ChatKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.chat_id
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    private Integer chatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.user_id
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    private Integer userId;

    public ChatKey() {
    }

    public ChatKey(Integer chatId, Integer userId) {
        this.chatId = chatId;
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.chat_id
     *
     * @return the value of chat.chat_id
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public Integer getChatId() {
        return chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.chat_id
     *
     * @param chatId the value for chat.chat_id
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public void setChatId(Integer chatId) {
        this.chatId = chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.user_id
     *
     * @return the value of chat.user_id
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.user_id
     *
     * @param userId the value for chat.user_id
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}