package com.zx.bean;

import com.google.gson.annotations.Expose;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Chat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.chat_id
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    @Expose
    private Integer chatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.chat_content
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    @Expose
    private String chatContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.chat_type
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    //0=system 1=text 2=image
    @Expose
    private Integer chatType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.chat_time
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    @Expose
    private Date chatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.chat_user_id
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    @Expose
    private Integer chatUserId;

    @Expose
    private Boolean type;

    @Expose
    User user;

    @Expose
    String userName;

    @Expose
    private List<User> userList = new ArrayList<>();

    @Expose
    private Boolean ban;

    public long getEndTime() {
        return endTime;
    }

    public void setEndTime(long endTime) {
        this.endTime = endTime;
    }

    @Expose
    private long endTime;



    public List<User> getUserList() {
        return userList;
    }

    public void setUserList(List<User> userList) {
        this.userList = userList;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }



    public Chat() {
    }

    public Chat(Integer chatId, String chatContent, Integer chatType, Date chatTime, Integer chatUserId, String userName, User user, Boolean type, List<User> userList, Boolean ban, long endTime) {
        this.chatId = chatId;
        this.chatContent = chatContent;
        this.chatType = chatType;
        this.chatTime = chatTime;
        this.chatUserId = chatUserId;
        this.userName = userName;
        this.user = user;
        this.type = type;
        this.userList = userList;
        this.ban = ban;
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.chat_id
     *
     * @return the value of chat.chat_id
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    public Integer getChatId() {
        return chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.chat_id
     *
     * @param chatId the value for chat.chat_id
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    public void setChatId(Integer chatId) {
        this.chatId = chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.chat_content
     *
     * @return the value of chat.chat_content
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    public String getChatContent() {
        return chatContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.chat_content
     *
     * @param chatContent the value for chat.chat_content
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    public void setChatContent(String chatContent) {
        this.chatContent = chatContent == null ? null : chatContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.chat_type
     *
     * @return the value of chat.chat_type
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    public Integer getChatType() {
        return chatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.chat_type
     *
     * @param chatType the value for chat.chat_type
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    public void setChatType(Integer chatType) {
        this.chatType = chatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.chat_time
     *
     * @return the value of chat.chat_time
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    public Date getChatTime() {
        return chatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.chat_time
     *
     * @param chatTime the value for chat.chat_time
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    public void setChatTime(Date chatTime) {
        this.chatTime = chatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.chat_user_id
     *
     * @return the value of chat.chat_user_id
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    public Integer getChatUserId() {
        return chatUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.chat_user_id
     *
     * @param chatUserId the value for chat.chat_user_id
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    public void setChatUserId(Integer chatUserId) {
        this.chatUserId = chatUserId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Override
    public String toString() {
        return "Chat{" +
                "chatId=" + chatId +
                ", chatContent='" + chatContent + '\'' +
                ", chatType=" + chatType +
                ", chatTime=" + chatTime +
                ", chatUserId=" + chatUserId +
                ", type=" + type +
                ", user=" + user +
                ", userName='" + userName + '\'' +
                ", userList=" + userList +
                ", ban=" + ban +
                '}';
    }

    public void setType(Boolean type) {
        this.type = type;
    }

    public void setBan(Boolean ban) {
        this.ban = ban;
    }

    public Boolean getType() {
        return type;
    }

    public Boolean getBan() {
        return ban;
    }
}