package com.zx.bean;

import com.google.gson.annotations.Expose;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Chat {
    /**
     * 聊天记录Id
     */
    @Expose
    private Integer chatId;

    /**
     * 聊天内容
     */
    @Expose
    private String chatContent;

    /**
     * 0=系统 1=文字 2=图片
     */
    @Expose
    private Integer chatType;

    /**
     * 聊天时间
     */
    @Expose
    private Date chatTime;

    /**
     * 聊天用户Id
     */
    @Expose
    private Integer chatUserId;
    /**
     * 0=上线 1=在线 2=离线
     */
    @Expose
    private Integer type;
    /**
     * 用户类
     */
    @Expose
    User user;
    /**
     * 用户名
     */
    @Expose
    String userName;
    /**
     * 用户列表
     */
    @Expose
    private List<User> userList = new ArrayList<>();
    /**
     * 是否被禁言
     */
    @Expose
    private Boolean ban;

    /**
     * 禁言截至时间
     */
    @Expose
    private long endTime;

    public long getEndTime() {
        return endTime;
    }

    public void setEndTime(long endTime) {
        this.endTime = endTime;
    }


    public List<User> getUserList() {
        return userList;
    }

    public void setUserList(List<User> userList) {
        this.userList = userList;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Chat() {
    }

    public Chat(Integer chatId, String chatContent, Integer chatType, Date chatTime, Integer chatUserId, String userName, User user, Integer type, List<User> userList, Boolean ban, long endTime) {
        this.chatId = chatId;
        this.chatContent = chatContent;
        this.chatType = chatType;
        this.chatTime = chatTime;
        this.chatUserId = chatUserId;
        this.userName = userName;
        this.user = user;
        this.type = type;
        this.userList = userList;
        this.ban = ban;
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.chat_id
     *
     * @return the value of chat.chat_id
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    public Integer getChatId() {
        return chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.chat_id
     *
     * @param chatId the value for chat.chat_id
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    public void setChatId(Integer chatId) {
        this.chatId = chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.chat_content
     *
     * @return the value of chat.chat_content
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    public String getChatContent() {
        return chatContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.chat_content
     *
     * @param chatContent the value for chat.chat_content
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    public void setChatContent(String chatContent) {
        this.chatContent = chatContent == null ? null : chatContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.chat_type
     *
     * @return the value of chat.chat_type
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    public Integer getChatType() {
        return chatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.chat_type
     *
     * @param chatType the value for chat.chat_type
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    public void setChatType(Integer chatType) {
        this.chatType = chatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.chat_time
     *
     * @return the value of chat.chat_time
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    public Date getChatTime() {
        return chatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.chat_time
     *
     * @param chatTime the value for chat.chat_time
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    public void setChatTime(Date chatTime) {
        this.chatTime = chatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.chat_user_id
     *
     * @return the value of chat.chat_user_id
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    public Integer getChatUserId() {
        return chatUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.chat_user_id
     *
     * @param chatUserId the value for chat.chat_user_id
     *
     * @mbg.generated Mon Apr 13 15:41:33 HKT 2020
     */
    public void setChatUserId(Integer chatUserId) {
        this.chatUserId = chatUserId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Override
    public String toString() {
        return "Chat{" +
                "chatId=" + chatId +
                ", chatContent='" + chatContent + '\'' +
                ", chatType=" + chatType +
                ", chatTime=" + chatTime +
                ", chatUserId=" + chatUserId +
                ", type=" + type +
                ", user=" + user +
                ", userName='" + userName + '\'' +
                ", userList=" + userList +
                ", ban=" + ban +
                '}';
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public void setBan(Boolean ban) {
        this.ban = ban;
    }

    public Integer getType() {
        return type;
    }

    public Boolean getBan() {
        return ban;
    }
}