package com.zx.bean;

public class Contact {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.contact_id
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    private Integer contactId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.contact_name
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.contact_phone
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    private String contactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.contact_address
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    private String contactAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.user_id
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    private Integer userId;

    public Contact() {
    }

    public Contact(Integer contactId, String contactName, String contactPhone, String contactAddress, Integer userId) {
        this.contactId = contactId;
        this.contactName = contactName;
        this.contactPhone = contactPhone;
        this.contactAddress = contactAddress;
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.contact_id
     *
     * @return the value of contact.contact_id
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public Integer getContactId() {
        return contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.contact_id
     *
     * @param contactId the value for contact.contact_id
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public void setContactId(Integer contactId) {
        this.contactId = contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.contact_name
     *
     * @return the value of contact.contact_name
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.contact_name
     *
     * @param contactName the value for contact.contact_name
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.contact_phone
     *
     * @return the value of contact.contact_phone
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.contact_phone
     *
     * @param contactPhone the value for contact.contact_phone
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.contact_address
     *
     * @return the value of contact.contact_address
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.contact_address
     *
     * @param contactAddress the value for contact.contact_address
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress == null ? null : contactAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.user_id
     *
     * @return the value of contact.user_id
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.user_id
     *
     * @param userId the value for contact.user_id
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}