package com.zx.bean;

public class ContactKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.contact_id
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    private Integer contactId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.user_id
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    private Integer userId;

    public ContactKey() {
    }

    public ContactKey(Integer contactId, Integer userId) {
        this.contactId = contactId;
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.contact_id
     *
     * @return the value of contact.contact_id
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public Integer getContactId() {
        return contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.contact_id
     *
     * @param contactId the value for contact.contact_id
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public void setContactId(Integer contactId) {
        this.contactId = contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.user_id
     *
     * @return the value of contact.user_id
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.user_id
     *
     * @param userId the value for contact.user_id
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}