package com.zx.bean;

public class Contact extends ContactKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.contact_name
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.contact_phone
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    private String contactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.contact_address
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    private String contactAddress;

    public Contact() {
    }

    public Contact(Integer contactId, Integer userId, String contactName, String contactPhone, String contactAddress) {
        super(contactId, userId);
        this.contactName = contactName;
        this.contactPhone = contactPhone;
        this.contactAddress = contactAddress;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.contact_name
     *
     * @return the value of contact.contact_name
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.contact_name
     *
     * @param contactName the value for contact.contact_name
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.contact_phone
     *
     * @return the value of contact.contact_phone
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.contact_phone
     *
     * @param contactPhone the value for contact.contact_phone
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.contact_address
     *
     * @return the value of contact.contact_address
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.contact_address
     *
     * @param contactAddress the value for contact.contact_address
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress == null ? null : contactAddress.trim();
    }
}