package com.zx.bean;

public class FileKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_id
     *
     * @mbg.generated Tue Mar 31 14:15:43 HKT 2020
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.user_id
     *
     * @mbg.generated Tue Mar 31 14:15:43 HKT 2020
     */
    private Integer userId;

    public FileKey() {
    }

    public FileKey(Integer fileId, Integer userId) {
        this.fileId = fileId;
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_id
     *
     * @return the value of file.file_id
     *
     * @mbg.generated Tue Mar 31 14:15:43 HKT 2020
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_id
     *
     * @param fileId the value for file.file_id
     *
     * @mbg.generated Tue Mar 31 14:15:43 HKT 2020
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.user_id
     *
     * @return the value of file.user_id
     *
     * @mbg.generated Tue Mar 31 14:15:43 HKT 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.user_id
     *
     * @param userId the value for file.user_id
     *
     * @mbg.generated Tue Mar 31 14:15:43 HKT 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}