package com.zx.bean;

import java.util.Date;

public class File extends FileKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_name
     *
     * @mbg.generated Tue Mar 31 14:15:43 HKT 2020
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_time
     *
     * @mbg.generated Tue Mar 31 14:15:43 HKT 2020
     */
    private Date fileTime;

    public File() {
    }

    public File(Integer fileId, Integer userId, String fileName, Date fileTime) {
        super(fileId, userId);
        this.fileName = fileName;
        this.fileTime = fileTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_name
     *
     * @return the value of file.file_name
     *
     * @mbg.generated Tue Mar 31 14:15:43 HKT 2020
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_name
     *
     * @param fileName the value for file.file_name
     *
     * @mbg.generated Tue Mar 31 14:15:43 HKT 2020
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_time
     *
     * @return the value of file.file_time
     *
     * @mbg.generated Tue Mar 31 14:15:43 HKT 2020
     */
    public Date getFileTime() {
        return fileTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_time
     *
     * @param fileTime the value for file.file_time
     *
     * @mbg.generated Tue Mar 31 14:15:43 HKT 2020
     */
    public void setFileTime(Date fileTime) {
        this.fileTime = fileTime;
    }
}