package com.zx.bean;

public class Image {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_id
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    private Integer imageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_name
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    private String imageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_url
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_md5
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    private String imageMd5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_like
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    private Integer imageLike;

    public Image() {
    }

    public Image(Integer imageId, String imageName, String imageUrl, String imageMd5, Integer imageLike) {
        this.imageId = imageId;
        this.imageName = imageName;
        this.imageUrl = imageUrl;
        this.imageMd5 = imageMd5;
        this.imageLike = imageLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_id
     *
     * @return the value of image.image_id
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public Integer getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_id
     *
     * @param imageId the value for image.image_id
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_name
     *
     * @return the value of image.image_name
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public String getImageName() {
        return imageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_name
     *
     * @param imageName the value for image.image_name
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public void setImageName(String imageName) {
        this.imageName = imageName == null ? null : imageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_url
     *
     * @return the value of image.image_url
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_url
     *
     * @param imageUrl the value for image.image_url
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_md5
     *
     * @return the value of image.image_md5
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public String getImageMd5() {
        return imageMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_md5
     *
     * @param imageMd5 the value for image.image_md5
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public void setImageMd5(String imageMd5) {
        this.imageMd5 = imageMd5 == null ? null : imageMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_like
     *
     * @return the value of image.image_like
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public Integer getImageLike() {
        return imageLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_like
     *
     * @param imageLike the value for image.image_like
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public void setImageLike(Integer imageLike) {
        this.imageLike = imageLike;
    }

    @Override
    public String toString() {
        return "Image{" +
                "imageId=" + imageId +
                ", imageName='" + imageName + '\'' +
                ", imageUrl='" + imageUrl + '\'' +
                ", imageMd5='" + imageMd5 + '\'' +
                ", imageLike=" + imageLike +
                '}';
    }
}