package com.zx.bean;

public class ImageLike {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imagelike.like_id
     *
     * @mbg.generated Mon Jun 01 16:04:02 HKT 2020
     */
    private Integer likeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imagelike.like_user_id
     *
     * @mbg.generated Mon Jun 01 16:04:02 HKT 2020
     */
    private Integer likeUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imagelike.like_image_id
     *
     * @mbg.generated Mon Jun 01 16:04:02 HKT 2020
     */
    private Integer likeImageId;

    public ImageLike() {
    }

    public ImageLike(Integer likeId, Integer likeUserId, Integer likeImageId) {
        this.likeId = likeId;
        this.likeUserId = likeUserId;
        this.likeImageId = likeImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imagelike.like_id
     *
     * @return the value of imagelike.like_id
     *
     * @mbg.generated Mon Jun 01 16:04:02 HKT 2020
     */
    public Integer getLikeId() {
        return likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imagelike.like_id
     *
     * @param likeId the value for imagelike.like_id
     *
     * @mbg.generated Mon Jun 01 16:04:02 HKT 2020
     */
    public void setLikeId(Integer likeId) {
        this.likeId = likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imagelike.like_user_id
     *
     * @return the value of imagelike.like_user_id
     *
     * @mbg.generated Mon Jun 01 16:04:02 HKT 2020
     */
    public Integer getLikeUserId() {
        return likeUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imagelike.like_user_id
     *
     * @param likeUserId the value for imagelike.like_user_id
     *
     * @mbg.generated Mon Jun 01 16:04:02 HKT 2020
     */
    public void setLikeUserId(Integer likeUserId) {
        this.likeUserId = likeUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imagelike.like_image_id
     *
     * @return the value of imagelike.like_image_id
     *
     * @mbg.generated Mon Jun 01 16:04:02 HKT 2020
     */
    public Integer getLikeImageId() {
        return likeImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imagelike.like_image_id
     *
     * @param likeImageId the value for imagelike.like_image_id
     *
     * @mbg.generated Mon Jun 01 16:04:02 HKT 2020
     */
    public void setLikeImageId(Integer likeImageId) {
        this.likeImageId = likeImageId;
    }

    @Override
    public String toString() {
        return "ImageLike{" +
                "likeId=" + likeId +
                ", likeUserId=" + likeUserId +
                ", likeImageId=" + likeImageId +
                '}';
    }
}