package com.zx.bean;

public class ImageMark {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imagemark.imagemark_id
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    private Integer imagemarkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imagemark.imagemark_user_id
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    private Integer imagemarkUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imagemark.imagemark_image_id
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    private Integer imagemarkImageId;

    public ImageMark() {
    }

    public ImageMark(Integer imagemarkId, Integer imagemarkUserId, Integer imagemarkImageId) {
        this.imagemarkId = imagemarkId;
        this.imagemarkUserId = imagemarkUserId;
        this.imagemarkImageId = imagemarkImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imagemark.imagemark_id
     *
     * @return the value of imagemark.imagemark_id
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public Integer getImagemarkId() {
        return imagemarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imagemark.imagemark_id
     *
     * @param imagemarkId the value for imagemark.imagemark_id
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public void setImagemarkId(Integer imagemarkId) {
        this.imagemarkId = imagemarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imagemark.imagemark_user_id
     *
     * @return the value of imagemark.imagemark_user_id
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public Integer getImagemarkUserId() {
        return imagemarkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imagemark.imagemark_user_id
     *
     * @param imagemarkUserId the value for imagemark.imagemark_user_id
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public void setImagemarkUserId(Integer imagemarkUserId) {
        this.imagemarkUserId = imagemarkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imagemark.imagemark_image_id
     *
     * @return the value of imagemark.imagemark_image_id
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public Integer getImagemarkImageId() {
        return imagemarkImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imagemark.imagemark_image_id
     *
     * @param imagemarkImageId the value for imagemark.imagemark_image_id
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public void setImagemarkImageId(Integer imagemarkImageId) {
        this.imagemarkImageId = imagemarkImageId;
    }
}