package com.zx.bean;

import java.util.ArrayList;
import java.util.List;

public class ImageMarkExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table imagemark
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table imagemark
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table imagemark
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemark
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public ImageMarkExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemark
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemark
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemark
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemark
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemark
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemark
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemark
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemark
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemark
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemark
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table imagemark
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andImagemarkIdIsNull() {
            addCriterion("imagemark_id is null");
            return (Criteria) this;
        }

        public Criteria andImagemarkIdIsNotNull() {
            addCriterion("imagemark_id is not null");
            return (Criteria) this;
        }

        public Criteria andImagemarkIdEqualTo(Integer value) {
            addCriterion("imagemark_id =", value, "imagemarkId");
            return (Criteria) this;
        }

        public Criteria andImagemarkIdNotEqualTo(Integer value) {
            addCriterion("imagemark_id <>", value, "imagemarkId");
            return (Criteria) this;
        }

        public Criteria andImagemarkIdGreaterThan(Integer value) {
            addCriterion("imagemark_id >", value, "imagemarkId");
            return (Criteria) this;
        }

        public Criteria andImagemarkIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("imagemark_id >=", value, "imagemarkId");
            return (Criteria) this;
        }

        public Criteria andImagemarkIdLessThan(Integer value) {
            addCriterion("imagemark_id <", value, "imagemarkId");
            return (Criteria) this;
        }

        public Criteria andImagemarkIdLessThanOrEqualTo(Integer value) {
            addCriterion("imagemark_id <=", value, "imagemarkId");
            return (Criteria) this;
        }

        public Criteria andImagemarkIdIn(List<Integer> values) {
            addCriterion("imagemark_id in", values, "imagemarkId");
            return (Criteria) this;
        }

        public Criteria andImagemarkIdNotIn(List<Integer> values) {
            addCriterion("imagemark_id not in", values, "imagemarkId");
            return (Criteria) this;
        }

        public Criteria andImagemarkIdBetween(Integer value1, Integer value2) {
            addCriterion("imagemark_id between", value1, value2, "imagemarkId");
            return (Criteria) this;
        }

        public Criteria andImagemarkIdNotBetween(Integer value1, Integer value2) {
            addCriterion("imagemark_id not between", value1, value2, "imagemarkId");
            return (Criteria) this;
        }

        public Criteria andImagemarkUserIdIsNull() {
            addCriterion("imagemark_user_id is null");
            return (Criteria) this;
        }

        public Criteria andImagemarkUserIdIsNotNull() {
            addCriterion("imagemark_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andImagemarkUserIdEqualTo(Integer value) {
            addCriterion("imagemark_user_id =", value, "imagemarkUserId");
            return (Criteria) this;
        }

        public Criteria andImagemarkUserIdNotEqualTo(Integer value) {
            addCriterion("imagemark_user_id <>", value, "imagemarkUserId");
            return (Criteria) this;
        }

        public Criteria andImagemarkUserIdGreaterThan(Integer value) {
            addCriterion("imagemark_user_id >", value, "imagemarkUserId");
            return (Criteria) this;
        }

        public Criteria andImagemarkUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("imagemark_user_id >=", value, "imagemarkUserId");
            return (Criteria) this;
        }

        public Criteria andImagemarkUserIdLessThan(Integer value) {
            addCriterion("imagemark_user_id <", value, "imagemarkUserId");
            return (Criteria) this;
        }

        public Criteria andImagemarkUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("imagemark_user_id <=", value, "imagemarkUserId");
            return (Criteria) this;
        }

        public Criteria andImagemarkUserIdIn(List<Integer> values) {
            addCriterion("imagemark_user_id in", values, "imagemarkUserId");
            return (Criteria) this;
        }

        public Criteria andImagemarkUserIdNotIn(List<Integer> values) {
            addCriterion("imagemark_user_id not in", values, "imagemarkUserId");
            return (Criteria) this;
        }

        public Criteria andImagemarkUserIdBetween(Integer value1, Integer value2) {
            addCriterion("imagemark_user_id between", value1, value2, "imagemarkUserId");
            return (Criteria) this;
        }

        public Criteria andImagemarkUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("imagemark_user_id not between", value1, value2, "imagemarkUserId");
            return (Criteria) this;
        }

        public Criteria andImagemarkImageIdIsNull() {
            addCriterion("imagemark_image_id is null");
            return (Criteria) this;
        }

        public Criteria andImagemarkImageIdIsNotNull() {
            addCriterion("imagemark_image_id is not null");
            return (Criteria) this;
        }

        public Criteria andImagemarkImageIdEqualTo(Integer value) {
            addCriterion("imagemark_image_id =", value, "imagemarkImageId");
            return (Criteria) this;
        }

        public Criteria andImagemarkImageIdNotEqualTo(Integer value) {
            addCriterion("imagemark_image_id <>", value, "imagemarkImageId");
            return (Criteria) this;
        }

        public Criteria andImagemarkImageIdGreaterThan(Integer value) {
            addCriterion("imagemark_image_id >", value, "imagemarkImageId");
            return (Criteria) this;
        }

        public Criteria andImagemarkImageIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("imagemark_image_id >=", value, "imagemarkImageId");
            return (Criteria) this;
        }

        public Criteria andImagemarkImageIdLessThan(Integer value) {
            addCriterion("imagemark_image_id <", value, "imagemarkImageId");
            return (Criteria) this;
        }

        public Criteria andImagemarkImageIdLessThanOrEqualTo(Integer value) {
            addCriterion("imagemark_image_id <=", value, "imagemarkImageId");
            return (Criteria) this;
        }

        public Criteria andImagemarkImageIdIn(List<Integer> values) {
            addCriterion("imagemark_image_id in", values, "imagemarkImageId");
            return (Criteria) this;
        }

        public Criteria andImagemarkImageIdNotIn(List<Integer> values) {
            addCriterion("imagemark_image_id not in", values, "imagemarkImageId");
            return (Criteria) this;
        }

        public Criteria andImagemarkImageIdBetween(Integer value1, Integer value2) {
            addCriterion("imagemark_image_id between", value1, value2, "imagemarkImageId");
            return (Criteria) this;
        }

        public Criteria andImagemarkImageIdNotBetween(Integer value1, Integer value2) {
            addCriterion("imagemark_image_id not between", value1, value2, "imagemarkImageId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table imagemark
     *
     * @mbg.generated do_not_delete_during_merge Mon Jun 01 14:08:27 HKT 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table imagemark
     *
     * @mbg.generated Mon Jun 01 14:08:27 HKT 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}