package com.zx.bean;

import java.util.Date;

public class NoteBook extends NoteBookKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notebook.notebook_title
     *
     * @mbg.generated Tue Mar 31 13:20:39 HKT 2020
     */
    private String notebookTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notebook.notebook_content
     *
     * @mbg.generated Tue Mar 31 13:20:39 HKT 2020
     */
    private String notebookContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notebook.notebook_time
     *
     * @mbg.generated Tue Mar 31 13:20:39 HKT 2020
     */
    private Date notebookTime;

    public NoteBook() {
    }

    public NoteBook(Integer notebookId, Integer userId, String notebookTitle, String notebookContent, Date notebookTime) {
        super(notebookId, userId);
        this.notebookTitle = notebookTitle;
        this.notebookContent = notebookContent;
        this.notebookTime = notebookTime;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notebook.notebook_title
     *
     * @return the value of notebook.notebook_title
     *
     * @mbg.generated Tue Mar 31 13:20:39 HKT 2020
     */
    public String getNotebookTitle() {
        return notebookTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notebook.notebook_title
     *
     * @param notebookTitle the value for notebook.notebook_title
     *
     * @mbg.generated Tue Mar 31 13:20:39 HKT 2020
     */
    public void setNotebookTitle(String notebookTitle) {
        this.notebookTitle = notebookTitle == null ? null : notebookTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notebook.notebook_content
     *
     * @return the value of notebook.notebook_content
     *
     * @mbg.generated Tue Mar 31 13:20:39 HKT 2020
     */
    public String getNotebookContent() {
        return notebookContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notebook.notebook_content
     *
     * @param notebookContent the value for notebook.notebook_content
     *
     * @mbg.generated Tue Mar 31 13:20:39 HKT 2020
     */
    public void setNotebookContent(String notebookContent) {
        this.notebookContent = notebookContent == null ? null : notebookContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notebook.notebook_time
     *
     * @return the value of notebook.notebook_time
     *
     * @mbg.generated Tue Mar 31 13:20:39 HKT 2020
     */
    public Date getNotebookTime() {
        return notebookTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notebook.notebook_time
     *
     * @param notebookTime the value for notebook.notebook_time
     *
     * @mbg.generated Tue Mar 31 13:20:39 HKT 2020
     */
    public void setNotebookTime(Date notebookTime) {
        this.notebookTime = notebookTime;
    }
}