package com.zx.bean;

public class NoteBook extends NoteBookKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notebook.notebook_title
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    private String notebookTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notebook.notebook_content
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    private String notebookContent;

    public NoteBook() {
    }

    public NoteBook(Integer notebookId, Integer userId, String notebookTitle, String notebookContent) {
        super(notebookId, userId);
        this.notebookTitle = notebookTitle;
        this.notebookContent = notebookContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notebook.notebook_title
     *
     * @return the value of notebook.notebook_title
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public String getNotebookTitle() {
        return notebookTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notebook.notebook_title
     *
     * @param notebookTitle the value for notebook.notebook_title
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public void setNotebookTitle(String notebookTitle) {
        this.notebookTitle = notebookTitle == null ? null : notebookTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notebook.notebook_content
     *
     * @return the value of notebook.notebook_content
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public String getNotebookContent() {
        return notebookContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notebook.notebook_content
     *
     * @param notebookContent the value for notebook.notebook_content
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    public void setNotebookContent(String notebookContent) {
        this.notebookContent = notebookContent == null ? null : notebookContent.trim();
    }
}