package com.zx.bean;

import java.util.Date;

public class NoteBook {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notebook.notebook_id
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    private Integer notebookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notebook.notebook_title
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    private String notebookTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notebook.notebook_content
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    private String notebookContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notebook.notebook_time
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    private Date notebookTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notebook.user_id
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    private Integer userId;

    public NoteBook() {
    }

    public NoteBook(Integer notebookId, String notebookTitle, String notebookContent, Date notebookTime, Integer userId) {
        this.notebookId = notebookId;
        this.notebookTitle = notebookTitle;
        this.notebookContent = notebookContent;
        this.notebookTime = notebookTime;
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notebook.notebook_id
     *
     * @return the value of notebook.notebook_id
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public Integer getNotebookId() {
        return notebookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notebook.notebook_id
     *
     * @param notebookId the value for notebook.notebook_id
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public void setNotebookId(Integer notebookId) {
        this.notebookId = notebookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notebook.notebook_title
     *
     * @return the value of notebook.notebook_title
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public String getNotebookTitle() {
        return notebookTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notebook.notebook_title
     *
     * @param notebookTitle the value for notebook.notebook_title
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public void setNotebookTitle(String notebookTitle) {
        this.notebookTitle = notebookTitle == null ? null : notebookTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notebook.notebook_content
     *
     * @return the value of notebook.notebook_content
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public String getNotebookContent() {
        return notebookContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notebook.notebook_content
     *
     * @param notebookContent the value for notebook.notebook_content
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public void setNotebookContent(String notebookContent) {
        this.notebookContent = notebookContent == null ? null : notebookContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notebook.notebook_time
     *
     * @return the value of notebook.notebook_time
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public Date getNotebookTime() {
        return notebookTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notebook.notebook_time
     *
     * @param notebookTime the value for notebook.notebook_time
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public void setNotebookTime(Date notebookTime) {
        this.notebookTime = notebookTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notebook.user_id
     *
     * @return the value of notebook.user_id
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notebook.user_id
     *
     * @param userId the value for notebook.user_id
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        return "NoteBook{" +
                "notebookId=" + notebookId +
                ", notebookTitle='" + notebookTitle + '\'' +
                ", notebookContent='" + notebookContent + '\'' +
                ", notebookTime=" + notebookTime +
                ", userId=" + userId +
                '}';
    }
}