package com.zx.dao;

import com.zx.bean.Chat;
import com.zx.bean.ChatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    long countByExample(ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    int deleteByExample(ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    int deleteByPrimaryKey(Integer chatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    int insert(Chat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    int insertSelective(Chat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    List<Chat> selectByExample(ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    Chat selectByPrimaryKey(Integer chatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    int updateByExampleSelective(@Param("record") Chat record, @Param("example") ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    int updateByExample(@Param("record") Chat record, @Param("example") ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    int updateByPrimaryKeySelective(Chat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    int updateByPrimaryKey(Chat record);

    List<Chat> selectByExampleWithUserName(ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Mon Apr 06 09:27:53 HKT 2020
     */
    Chat selectByPrimaryKeyWithUserName(Integer chatId);
}