package com.zx.dao;

import com.zx.bean.Cloud;
import com.zx.bean.CloudExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CloudMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud
     *
     * @mbg.generated Fri May 08 16:04:33 HKT 2020
     */
    long countByExample(CloudExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud
     *
     * @mbg.generated Fri May 08 16:04:33 HKT 2020
     */
    int deleteByExample(CloudExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud
     *
     * @mbg.generated Fri May 08 16:04:33 HKT 2020
     */
    int deleteByPrimaryKey(Integer cloudId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud
     *
     * @mbg.generated Fri May 08 16:04:33 HKT 2020
     */
    int insert(Cloud record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud
     *
     * @mbg.generated Fri May 08 16:04:33 HKT 2020
     */
    int insertSelective(Cloud record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud
     *
     * @mbg.generated Fri May 08 16:04:33 HKT 2020
     */
    List<Cloud> selectByExample(CloudExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud
     *
     * @mbg.generated Fri May 08 16:04:33 HKT 2020
     */
    Cloud selectByPrimaryKey(Integer cloudId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud
     *
     * @mbg.generated Fri May 08 16:04:33 HKT 2020
     */
    int updateByExampleSelective(@Param("record") Cloud record, @Param("example") CloudExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud
     *
     * @mbg.generated Fri May 08 16:04:33 HKT 2020
     */
    int updateByExample(@Param("record") Cloud record, @Param("example") CloudExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud
     *
     * @mbg.generated Fri May 08 16:04:33 HKT 2020
     */
    int updateByPrimaryKeySelective(Cloud record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud
     *
     * @mbg.generated Fri May 08 16:04:33 HKT 2020
     */
    int updateByPrimaryKey(Cloud record);
}