package com.zx.dao;

import com.zx.bean.Contact;
import com.zx.bean.ContactExample;
import com.zx.bean.ContactKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    long countByExample(ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    int deleteByExample(ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    int deleteByPrimaryKey(ContactKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    int insert(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    int insertSelective(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    List<Contact> selectByExample(ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    Contact selectByPrimaryKey(ContactKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    int updateByExampleSelective(@Param("record") Contact record, @Param("example") ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    int updateByExample(@Param("record") Contact record, @Param("example") ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    int updateByPrimaryKeySelective(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Sun Mar 29 18:31:27 HKT 2020
     */
    int updateByPrimaryKey(Contact record);
}