package com.zx.dao;

import com.zx.bean.ImageLike;
import com.zx.bean.ImageLikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImageLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagelike
     *
     * @mbg.generated Mon Jun 01 16:04:02 HKT 2020
     */
    long countByExample(ImageLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagelike
     *
     * @mbg.generated Mon Jun 01 16:04:02 HKT 2020
     */
    int deleteByExample(ImageLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagelike
     *
     * @mbg.generated Mon Jun 01 16:04:02 HKT 2020
     */
    int deleteByPrimaryKey(Integer likeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagelike
     *
     * @mbg.generated Mon Jun 01 16:04:02 HKT 2020
     */
    int insert(ImageLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagelike
     *
     * @mbg.generated Mon Jun 01 16:04:02 HKT 2020
     */
    int insertSelective(ImageLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagelike
     *
     * @mbg.generated Mon Jun 01 16:04:02 HKT 2020
     */
    List<ImageLike> selectByExample(ImageLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagelike
     *
     * @mbg.generated Mon Jun 01 16:04:02 HKT 2020
     */
    ImageLike selectByPrimaryKey(Integer likeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagelike
     *
     * @mbg.generated Mon Jun 01 16:04:02 HKT 2020
     */
    int updateByExampleSelective(@Param("record") ImageLike record, @Param("example") ImageLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagelike
     *
     * @mbg.generated Mon Jun 01 16:04:02 HKT 2020
     */
    int updateByExample(@Param("record") ImageLike record, @Param("example") ImageLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagelike
     *
     * @mbg.generated Mon Jun 01 16:04:02 HKT 2020
     */
    int updateByPrimaryKeySelective(ImageLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagelike
     *
     * @mbg.generated Mon Jun 01 16:04:02 HKT 2020
     */
    int updateByPrimaryKey(ImageLike record);
}